### Promise简介

表示一个异步操作的最终状态（完成或失败），以及其返回的值。它允许你为异步操作的成功和失败分别绑定相应的处理方法（handlers）。 这让异步方法可以像同步方法那样返回值，但并不是立即返回最终执行结果，而是一个能代表未来出现的结果的promise对象。

一个 `Promise`有以下几种状态:

- *pending*: 初始状态，既不是成功，也不是失败状态。
- *fulfilled*: 意味着操作成功完成。
- *rejected*: 意味着操作失败。

1. pending 状态的 Promise 对象可能触发fulfilled 状态并传递一个值给相应的状态处理方法，也可能触发失败状态（rejected）并传递失败信息。
2. 当其中任一种情况出现时，Promise 对象的 `then` 方法绑定的处理方法（handlers ）就会被调用，其中分别是Promise状态为*fulfilled*时，调用 then 的 onfulfilled 方法，和Promise状态为*rejected*时，调用 then 的 onrejected 方法。
3. 因为 `Promise.prototype.then` 和  `Promise.prototype.catch` 方法返回promise 对象， 所以它们可以被链式调用。

![](E:\WebStorm_Dir\articles\images\promises (2).png)

![](E:\WebStorm_Dir\articles\images\res&rej.png)

由上述可以看出，一个一步函数代码就是返回一个具有resolve和reject情况的promise对象。







promise是异步编程的一种解决方案，它出现的初衷是为了解决回调地狱的问题。

打个比方，我需要：--(延迟1s)--> 输出1 --(延迟2s)--> 输出2 --(延迟3s)--> 输出3，通常写法：

```javascript
// promise的出现就是为了解决回调地狱问题
setTimeout(() => {
    console.log('1');
    setTimeout(() => {
        console.log('2');
        setTimeout(() => {
            console.log('3');
        }, 3000)
    }, 2000)
}, 1000); 
```

这样的多重的嵌套的回调被称为回调地狱，这样的代码可读性很差，不利于理解。如下使用promise来替换：

```javascript
// promise替换回调地狱的方式
function delay(time, num) {
    return new Promise((res, rej) => {
        setTimeout(() => {
            console.log(num);
            res();
        }, time * 1000)
    });
}
// 将之前的回调地狱改成了几乎类似于同步执行的格式
delay(1, 1).then(() => {
    return delay(2, 2);
}).then(() => {
    delay(3, 3);
}); 
```

### Promise的使用

Promise的基本使用方式如下：

```javascript
//回调函数的基本使用格式
new Promise((resolve, reject) => {
    if ('some option') {
        resolve('some value');
    } else {
        reject('some error');
    }
}).then(
    val => {
        // ...
    },
    error => {
        // ...
    }
); 
```

Promise构造函数接收一个函数型参数fn，fn有两个参数，分别是：resolve、reject，这两个方法都有返回值作为后续succ和error回调的参数，Promise还有一个Promise.prototype.then方法，该方法接收两个参数，分别是成功的回调函数succ和失败的回调函数error。

在fn中调用resolve会触发then中的succ回调，调用reject会触发error回调。

#### 2.1 参数传递

在fn内部调用resolve/reject传入的参数会作为相应参数传入相应的回调函数（如下面res中的参数“happy”，会作为then进行succ回调函数的参数val，rej的参数“error”会作为error回调函数的参数err）

```javascript
// Promise内部的参数传递
new Promise((res, rej) => {
    res('happy')
}).then(val => { // 将上面的resolve返回值传给val
    console.log(val);  // happy
});
new Promise((res, rej) => {
    rej('error!');
}).then( val => {},err => { // 将上面的reject返回值传给err
        console.log(err);  // error!
    }
); 
```

链式调用时若上一级没有传递值（没有返回值）则默认为undefined

```javascript
// 上一级没有传递值，则默认返回undefined
new Promise((res, rej) => {
    res('a');        // return a;
}).then(val => {     // val=a
    return 'b'       // return "b"
}).then(val => {     // val=b
    console.log(val);  // 'b'
}).then((val) => {     // val="undefined"
    console.log(val);  // 'undefined'
}); 
```

若上一级的then中传递的并非函数，则忽略该级

```javascript
// 若上一级的then中传递的并非函数，则忽略该级
new Promise((res, rej)=> {
    res('a');           //return a
}).then(val=> {         //val=a
    return 'b';         //return b
}).then(val=> {         //val=b
    console.log(val);   // “b”
    return 'c';         //return c;
}).then({
    name: 'lan'         // 并非函数，而是一个对象
}).then((val)=> {       //上一层不是函数，直接忽略，再读取上上层的返回值作为参数，val=c
    console.log(val);   // “c”
}); 
```

对于单一参数的返回形式，可以直接使用该函数名代替：

```js
get('story.json').then(function(response) {
  return JSON.parse(response);
}).then(function(response) {
  console.log("Yey JSON!", response);
})
//等价于
get('story.json').then(JSON.parse).then(function(response) {
  console.log("Yey JSON!", response);
})
//等价于
function getJSON(url) {
  return get(url).then(JSON.parse)；
}
```



#### 2.2 参数传递例题

```
/*  参数传递案例  */
let doSomething = function () {
    return new Promise((resolve, reject) => {
        resolve('返回值');
    });
};
let doSomethingElse = function () {
    return '新的值';
};
doSomething().then(function () {
    return doSomethingElse();   //= return '新的值';
}).then(resp => {               //resp=“新的值”
    console.warn(resp);
    console.warn('1 =========<');
});
doSomething().then(function () {
    // = "新的值"
    doSomethingElse();  //因为执行函数之后返回的是一个字符串，所以此行就是一行字符串====“新的值”,没有返回值
}).then(resp => {       //resp="undefined"
    console.warn(resp);
    console.warn('2 =========<');
});
doSomething().then(doSomethingElse())//then 里面不是一个函数，是一个字符串，所以直接忽略该级，resp=resovle("返回值")
    .then(resp => {
        console.warn(resp);         //resovle("返回值")，得出resp=“返回值”
        console.warn('3 =========<');
    });
doSomething().then(doSomethingElse).then(resp => {//doSomethingElse==return "新的值"，resp=“新的值”
    console.warn(resp);
    console.warn('4 =========<');
});
```

### Promise的原型方法

#### Promise.prototype.then

当Promise中的状态(pending ---> resolved or rejected)发生变化时才会执行then方法。

调用then返回的依旧是一个Promise实例 ( 所以才可以链式调用... )

```javascript
// Promise.prototype.then
new Promise((res, rej)=> {
    res('a');
}).then(val=> {
    return 'b';
});
// then返回的依然是一个promise对象，上面等同于
new Promise((res, rej)=> {
    res('a');
}).then(val=> {
    return new Promise((res, rej)=> {
        res('b');
    });
}); 
```

then中的回调总会异步执行

```javascript
// then中的回调总是会异步执行的（完成顶级作用域中的代码最后一行之后）
new Promise((res, rej) => {
    console.log('a');
    res('');
}).then(() => {
    console.log('b');
});
console.log('c');//此行代码是顶级作用域中的最后一行代码
// 输出顺序为： a c b 
```

如果你不在Promise的参数函数中调用resolve或者reject那么then方法永远不会被触发，因为这样他没有返回的Promise对象，then中只要是函数参数，都会返回Promise对象。

```javascript
// 如果不在Promise的构造函数中调用resolve和reject，then方法永远不会被执行
new Promise((res, rej) => {
    console.log('a');
}).then(() => {
    console.log('b');
});
console.log('c');
// a c 
```

#### Promise.prototype.catch()

Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。

如果该对象状态变为resolved，则会调用then方法指定的回调函数；如果异步操作抛出错误，状态就会变为rejected，就会调用catch方法指定的回调函数，处理这个错误。另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。

Promise 在resolve语句后面，再抛出错误，不会被捕获，等于没有抛出。因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。

传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。

一般总是建议，Promise 对象后面要跟catch方法，这样可以处理 Promise 内部发生的错误。catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。

```javascript
/*  Promise.prototype.catch() */
// Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。
new Promise((res, rej) => {
    rej('a');
}).then(val => {
    },
    err => {
        console.log(err);
    }
);
```

#### Promise.prototype.finally

用于指定不管 Promise 对象最后状态如何，都会执行的操作。不管promise最后的状态，在执行完then或catch指定的回调函数以后，都会执行finally方法指定的回调函数。

finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。这表明，finally方法里面的操作，应该是**与状态无关的，不依赖于 Promise 的执行结果**。

### Promise的静态方法

Promise还有四个静态方法，分别是resolve、reject、all、race，下面我们一一介绍一下。

#### Promise.resolve()

除了通过new Promise()的方式，我们还有两种创建Promise对象的方法，Promise.resolve()相当于创建了一个立即resolve的对象。如下两段代码作用相同：

```javascript
// Promise.resolve()与Promise.reject()
//相当于创建了一个立即resolve或者reject的Promise对象。
Promise.resolve("a");
// 等价于
new Promise((res,rej)=>{
    res("a");
}); 
```

当然根据传入的参数不同，Promise.resolve()也会做出不同的操作。

- 如果参数是 Promise 实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例。

- 参数是一个thenable对象，thenable对象指的是具有then方法的对象，比如下面这个对象。

```javascript
let thenable = {
    then: function(resolve, reject) {
        resolve(42);
    }
}; 
```

Promise.resolve方法会将这个对象转为 Promise对象，然后就立即执行thenable对象的then方法。

- 参数不是具有then方法的对象，或根本就不是对象

如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的 Promise 对象，状态为resolved。

- 不带有任何参数

Promise.resolve方法允许调用时不带参数，直接返回一个resolved状态的 Promise 对象。

值得注意的一点是该静态方法是在本次事件轮询结束前调用，而不是在下一次事件轮询开始时调用。关于事件轮询可以看这里——>[JavaScript 运行机制详解：再谈Event Loop](https://link.juejin.im?target=http%3A%2F%2Fwww.ruanyifeng.com%2Fblog%2F2014%2F10%2Fevent-loop.html)

#### Promise.reject()

和Promise.resolve()类似，只不过一个是触发成功的回调，一个是触发失败的回调

#### Promise.all()

Promise的all方法提供了并行执行异步操作的能力，并且在所有异步操作执行完后才执行回调。 

用Promise.all来执行，all接收一个数组参数，里面的值最终都算返回Promise对象。这样，三个异步操作的并行执行的，等到它们都执行完后才会进到then里面。有了all，你就可以并行执行多个异步操作，并且在一个回调中处理所有的返回数据。

```javascript
// Promise的all方法提供了并行执行异步操作的能力，并且在所有Promise异步操作执行完后才执行then方法。
function asyncFun1() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('a');
        }, 1000);
    });
}
function asyncFun2() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('b');
        }, 1000);
    });
}
function asyncFun3() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('c');
        }, 1000);
    });
}
// all是全部执行完毕再输出，所以输出abc
Promise.all([asyncFun1(),asyncFun2(),asyncFun3()]).then((value =>{
    console.log(value);//  输出：['a','b','c']
}));
```

适用场景：打开网页时，预先加载需要用到的各种资源如图片、flash以及各种静态文件。所有的都加载完后，我们再进行页面的初始化。

#### Promise.race()

race()和all相反，all()是数组中所有Promise都执行完毕就执行then，而race()是一旦有一个Promise执行完毕就会执行then()，用上面的三个Promise返回值函数举例。

Promise.all()与Promise.race()方法接受一个数组作为参数，将参数转为 Promise 实例，再进一步处理，不过Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。

```javascript
// Promise的race方法与all方法恰好相反，只要有一个Promise执行完毕就会执行then方法
function asyncFun1() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('a');
        }, 1000);
    });
}
function asyncFun2() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('b');
        }, 1000);
    });
}
function asyncFun3() {
    return new Promise((res, rej)=> {
        setTimeout(()=> {
            res('c');
        }, 1000);
    });
}
// 首先all与race方法都是接受一个数组参数，里面的值最终都是返回Promise对象
// race是只要有一个执行完毕就输出，所以输出a
Promise.race([asyncFun1(),asyncFun2(),asyncFun3()]).then((value => {
    console.log(value);//   输出：a
}));
```



### 链式调用案例

看了这么多关于Promise的知识，我们来做一道题巩固一下。

写一个类Man实现以下链式调用 调用方式： new Man('lan').sleep(3).eat('apple').sleep(5).eat('banana'); 打印： 'hello, lan' -(等待3s)--> 'lan eat apple' -(等待5s)--> 'lan eat banana' 

思路：

- 在原型方法中返回this达到链式调用的目的
- 等待3s执行的效果可以用Promise & then实现

具体实现如下：

```javascript
class Man {

    constructor(name){

        this.name=name;

        this.sayName();

        this.rope=Promise.resolve();//定义全局Promise作链式调用

    }

    sayName(){

        console.log(`Hello , ${this.name}`);

    }

    sleep(time){

        this.rope=this.rope.then(()=>{

            return new Promise(((resolve, reject) => {

                setTimeout(()=>{

                    resolve();

                },time*1000)

            }))

        });

        return this;

    }

    eat(food){

        this.rope=this.rope.then(()=>{

            console.log(`${this.name} is eating ${food}`);

        });

        return this;

    }

}

new Man('lan').sleep(3).eat('apple').sleep(5).eat('banana'); 
```

ok！不知道你有没有看懂呢？如果能完全理解代码那你的Promise可以通关了，顺便来个小思考,下面这种写法可以吗？和上面相比有什么区别？：

```javascript
class Man {

    constructor(name) {

        this.name = name;

        this.sayName();

    }

    sayName() {

        console.log(`hello, ${this.name}`);

    }

    sleep(time) {

        this.rope = new Promise((res, rej)=> {//每一次调用sleep都会new一个新的Promise对象，因此每个sleep都是异步执行的，互不影响，因此一个在time=3时输出，一个在time=5时输出，而不是3和8

            setTimeout(()=> {

                res();

            }, time*1000);

        });

        return this;

    }

    eat(food) {

        this.rope = this.rope.then(()=> {

            console.log(`${this.name} eat ${food}`);

        });

        return this;

    }

}

new Man('lan').sleep(3).eat('apple').sleep(5).eat('banana'); 
```

简单的说，第二段代码的执行结果是（第三秒输出一个，第五秒输出一个）

'hello, lan' -(等待3s)--> 'lan eat apple' -（等待5-3秒）---> 'lan eat banana' 

为什么会出现这种差别？ 因为第二段代码每一次调用sleep都会new一个新的Promise对象，因此每个sleep都是异步执行的，互不影响，因此一个在time=3时输出，一个在time=5时输出，而不是3和8



和以下情况类似

var time1 = setTimeout(()=> {

    console.log('a');

}, 1000);

//两个定时器之间互不影响

var time2 = setTimeout(()=> {

    console.log('b');

}, 1000);

// 同时输出 a b 

抽象一点的讲解是：

// 第一段正确的代码的执行为 var p1 = new Promise().then('停顿3s').then('打印食物').then('停顿5s').then('打印食物'); // 第二段代码的执行行为，p1、p2异步并行执行 var p1 = new Promise().then('停顿3s').then('打印食物'); var p2 = new Promise().then('停顿5s').then('打印食物');与上一个操作间隔2秒 

### 总结

Promise的经常用到的地方：

- 摆脱回调地狱，但是并没有从根本上解决回调复杂的问题，只是看起来会规范一些。
- 多个异步任务同步